{% set version = '1.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcdd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rcdd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rcdd/rcdd_{{ version }}.tar.gz
  sha256: 9f8acd8cad398369e93067196baa26d2d3109ce8d34daa1436f7bed42473db75

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'
    - '*/libgmp-10.dll'

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - {{ posix }}gmp
  run:
    - r-base
test:
  commands:
    - $R -e "library('rcdd')"           # [not win]
    - "\"%R%\" -e \"library('rcdd')\""  # [win]

about:
  home: https://www.stat.umn.edu/geyer/rcdd/, https://github.com/cjgeyer/rcdd
  license: GPL-2.0-only
  summary: 'R interface to (some of) cddlib (<https://github.com/cddlib/cddlib>). Converts back
    and forth between two representations of a convex polytope: as solution of a set
    of linear equalities and inequalities and as convex hull of set of points and rays.
    Also does linear programming and redundant generator elimination (for example, convex
    hull in n dimensions).  All functions can use exact infinite-precision rational
    arithmetic.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - Rassine

# Package: rcdd
# Version: 1.6
# Date: 2023-12-14
# Title: Computational Geometry
# Author: Charles J. Geyer <geyer@umn.edu> and Glen D. Meeden <gmeeden@umn.edu>, incorporates code from cddlib (ver 0.94f) written by Komei Fukuda <fukuda@ifor.math.ethz.ch>
# Maintainer: Charles J. Geyer <geyer@umn.edu>
# Depends: R (>= 3.0.2)
# Imports: methods
# SystemRequirements: GMP (GNU MP bignum library from <https://gmplib.org/>)
# Description: R interface to (some of) cddlib (<https://github.com/cddlib/cddlib>). Converts back and forth between two representations of a convex polytope: as solution of a set of linear equalities and inequalities and as convex hull of set of points and rays. Also does linear programming and redundant generator elimination (for example, convex hull in n dimensions).  All functions can use exact infinite-precision rational arithmetic.
# License: GPL-2
# URL: https://www.stat.umn.edu/geyer/rcdd/, https://github.com/cjgeyer/rcdd
# NeedsCompilation: yes
# Packaged: 2023-12-14 16:53:06 UTC; geyer
# Repository: CRAN
# Date/Publication: 2023-12-15 09:40:02 UTC
